### ISSUE TITLE
word-lock problem

### ISSUE THREAD

**Issue by sachincool** [zaratec/miniCTF-platform#2]
the readme of this challenge is not correct. Maybe It's still in the construction phase.  

P.s I like some help if possible, 
I Know using || and 1=1#  is the right way the only thing left for me to do is break out of the context of (') single quote... 
I dunno how I can achieve that in a post request. would've used URL encoding for Get requests.. 
any guidance would be appreciated, Ty

**Comment by sachincool** [comment]
figured it out, Nm Sorry to disturb you.

**Comment by zwade** [comment]
Glad you got it!
